#!/bin/bash -xe
ssh-keyscan -t rsa 【TARGETIP】 >> ~/.ssh/known_hosts
ssh -i /var/lib/jenkins/.ssh/private.pem 【TARGETUSER】@【TARGETIP】 "cd /home/【TARGETUSER】/work; if [[ ! -d /home/【TARGETUSER】/work/【REPOSITRY】 ]]; then mkdir 【REPOSITRY】; cd 【REPOSITRY】; git init; fi; cd 【REPOSITRY】; git pull https://github.com/【GITUSER】/【REPOSITRY】.git"
